version: '3.8'

services:
  scraper:
    build: .
    container_name: web-scraper-gcp
    volumes:
      - ./src:/app/src  # Mount the src directory for development
      - ./screenshots:/tmp/screenshots
    command: ["python", "src/scraper.py"]
    # If you need Google Cloud credentials locally, uncomment and configure:
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/keyfile.json
    # volumes:
    #   - ./path/to/your/keyfile.json:/path/to/your/keyfile.json:ro
